/*
 * File: app/store/RdgUsersStore.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.store.RdgUsersStore', {
    extend: 'Ext.data.Store',
    alias: 'store.rdgusersstore',

    requires: [
        'Tel.model.IagUsersModel',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    config: {
        autoLoad: true,
        model: 'Tel.model.IagUsersModel',
        remoteFilter: true,
        storeId: 'RdgUsersStore',
        syncRemovedRecords: false,
        proxy: {
            type: 'jsonp',
            url: 'https://vasil.iag.bg/tel/allusers/users_by_podelenia',
            reader: {
                type: 'json',
                rootProperty: 'records'
            }
        }
    }
});