/*
 * File: app/view/Container.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.view.Container', {
    extend: 'Ext.Container',

    requires: [
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.plugin.ListPaging'
    ],

    config: {
        itemId: 'mycontainer',
        layout: 'fit',
        items: [
            {
                xtype: 'searchfield',
                docked: 'top',
                id: 'search',
                itemId: 'search',
                margin: 5,
                padding: 10
            },
            {
                xtype: 'list',
                id: 'alluserslist',
                margin: 5,
                emptyText: 'Няма запис',
                itemTpl: [
                    '',
                    '<table>',
                    '    <tr>',
                    '        <td style="padding:20px"><img src="https://vasil.iag.bg/upload/1/{picture}" width="80" heigh="80"></img></td>',
                    '        <td>',
                    '            <table>',
                    '                <tr>',
                    '                    <td>{titla} {ime} {prez} {fam}</td>',
                    '                </tr> ',
                    '                <tr>',
                    '                    <td>{pod}</td>',
                    '                </tr>',
                    '                <tr>',
                    '                    <td>{tel}</td>',
                    '                </tr>',
                    '                <tr>',
                    '                    <td>{email}</td>',
                    '                </tr>',
                    '                <tr>',
                    '                    <td>{dlagnost}</td>',
                    '                </tr>',
                    '            </table>',
                    '            ',
                    '            ',
                    '        </td>',
                    '         ',
                    '    </tr>',
                    '</table',
                    '',
                    '',
                    ''
                ],
                store: 'Store',
                plugins: [
                    {
                        autoPaging: true,
                        loadMoreText: 'Зареждам още ...',
                        noMoreRecordsText: 'Няма повече записи',
                        type: 'listpaging'
                    }
                ]
            }
        ]
    }

});