/*
 * File: app/view/Container.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.view.Container', {
    extend: 'Ext.Container',

    requires: [
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.plugin.ListPaging'
    ],

    config: {
        itemId: 'mycontainer',
        layout: 'fit',
        scrollable: true,
        items: [
            {
                xtype: 'searchfield',
                docked: 'top',
                id: 'search',
                itemId: 'search',
                margin: 5,
                labelAlign: 'top'
            },
            {
                xtype: 'list',
                id: 'alluserslist',
                margin: 5,
                autoDestroy: false,
                emptyText: 'Няма запис',
                itemTpl: [
                    '',
                    '<table>',
                    '    <tr>',
                    '        <td style=""><img src="https://vasil.iag.bg/upload/{glav_pod}/{picture}" width="80" heigh="80"></img></td>',
                    '        <td>',
                    '            <table>',
                    '                <tbody style="text-align:center">',
                    '                    <tr>',
                    '                        <td><small><b>{titla} {ime} {fam}</b></small></td>',
                    '                    </tr> ',
                    '                    <tr>',
                    '                        <td><small>{pod}</small></td>',
                    '                    </tr>',
                    '                    <tr>',
                    '                        <td><small>{tel}<small></td>',
                    '                    </tr>',
                    '                    <tr>',
                    '                        <td><small>{email}<small></td>',
                    '                    </tr>',
                    '                    <tr>',
                    '                        <td><small>{dlagnost}<small></td>',
                    '                    </tr>',
                    '                </tbody>        ',
                    '            </table>',
                    '            ',
                    '            ',
                    '        </td>',
                    '         ',
                    '    </tr>',
                    '</table>'
                ],
                store: 'Store',
                plugins: [
                    {
                        autoPaging: true,
                        loadMoreText: 'Зареждам още ...',
                        noMoreRecordsText: 'Няма повече записи',
                        type: 'listpaging'
                    }
                ]
            }
        ]
    }

});