/*
 * File: app/view/MainMenuPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.view.MainMenuPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.mainmenupanel',

    requires: [
        'Ext.Panel',
        'Ext.Img',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'panel',
                flex: 2,
                layout: 'fit',
                items: [
                    {
                        xtype: 'image',
                        src: 'resources/images/main.png'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 2,
                margin: 30,
                layout: 'vbox',
                items: [
                    {
                        xtype: 'panel',
                        flex: 1,
                        padding: '',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                id: 'iagBtn',
                                ui: 'action-small',
                                iconAlign: 'center',
                                text: 'ИАГ'
                            },
                            {
                                xtype: 'spacer',
                                width: 10
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                disabled: false,
                                id: 'rdgBtn',
                                ui: 'action-small',
                                text: 'РДГ / ДП / ИАГ под.'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 1,
                        margin: '10 0',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                id: 'dgsBtn',
                                ui: 'action-small',
                                text: 'ДГС / ДЛС'
                            },
                            {
                                xtype: 'spacer',
                                width: 10
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                id: 'searchBtn',
                                ui: 'action-small',
                                iconAlign: 'center',
                                iconCls: 'search'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 1,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                disabled: true,
                                id: 'podBtn',
                                ui: 'action-small'
                            },
                            {
                                xtype: 'spacer',
                                width: 10
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                id: 'aboutBtn',
                                ui: 'action-small',
                                text: 'За приложението'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                modal: false
            }
        ]
    }

});