/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.view.Main', {
    extend: 'Ext.navigation.View',
    alias: 'widget.main',

    requires: [
        'Tel.view.MainMenuPanel',
        'Ext.Panel'
    ],

    config: {
        id: 'main',
        itemId: '',
        defaultBackButtonText: '<-',
        layout: {
            type: 'card',
            animation: 'fade'
        },
        items: [
            {
                xtype: 'mainmenupanel',
                title: 'Изпълнителна агенция по горите'
            }
        ]
    }

});