/*
 * File: app/view/RdgDgsList.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.view.RdgDgsList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.rdgdgslist',

    requires: [
        'Ext.XTemplate',
        'Ext.plugin.ListPaging'
    ],

    config: {
        id: 'rdgdgslist',
        loadingText: 'Зареждам ...',
        store: 'RdgDgsStore',
        onItemDisclosure: true,
        itemTpl: [
            '<div>{podelenie}</div>'
        ],
        plugins: [
            {
                autoPaging: true,
                loadMoreText: 'Зареждам още ..',
                noMoreRecordsText: 'Няма повече записи',
                type: 'listpaging'
            }
        ]
    }

});