/*
 * File: app/view/RdgUsersList.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.view.RdgUsersList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.rdguserslist',

    requires: [
        'Ext.XTemplate',
        'Ext.plugin.ListPaging'
    ],

    config: {
        itemId: 'rdguserslist',
        emptyText: 'Няма такъв служител',
        loadingText: 'Зареждам ...',
        store: 'RdgUsersStore',
        itemTpl: [
            '<table>',
            '    <tr>',
            '        <td style="padding:20px"><img src="https://vasil.iag.bg/upload/{glav_pod}/{picture}" width="80" heigh="80"></img></td>',
            '        <td>',
            '            <table>',
            '                <tr>',
            '                    <td><b>{titla} {ime} {fam}</b></td>',
            '                </tr> ',
            '                <tr>',
            '                    <td><small>{pod}</small></td>',
            '                </tr>',
            '                <tr>',
            '                    <td><small>{tel}</small></td>',
            '                </tr>',
            '                <tr>',
            '                    <td><small>{email}</small></td>',
            '                </tr>',
            '                <tr>',
            '                    <td><small>{dlagnost}</small></td>',
            '                </tr>',
            '            </table>',
            '            ',
            '            ',
            '        </td>',
            '         ',
            '    </tr>',
            '</table>'
        ],
        plugins: [
            {
                pluginId: 'myplugin',
                autoPaging: true,
                loadMoreText: 'Зареждам още ...',
                noMoreRecordsText: 'Няма повече записи',
                type: 'listpaging'
            }
        ]
    }

});