/*
 * File: app/model/IagUsersModel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.model.IagUsersModel', {
    extend: 'Ext.data.Model',
    alias: 'model.iagusersmodel',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id',
                sortType: 'asInt',
                type: 'int'
            },
            {
                name: 'ime'
            },
            {
                name: 'titla'
            },
            {
                name: 'prez'
            },
            {
                name: 'fam'
            },
            {
                name: 'pod'
            },
            {
                name: 'tel'
            },
            {
                name: 'glav_pod'
            },
            {
                name: 'email'
            },
            {
                name: 'picture'
            },
            {
                name: 'egn'
            },
            {
                name: 'dlagnost'
            },
            {
                name: 'directorate'
            },
            {
                name: 'directorate_badj'
            },
            {
                name: 'pod_id'
            }
        ]
    }
});