/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'IagUsersModel',
        'Podelenia'
    ],
    stores: [
        'Store',
        'IagStore',
        'RdgStore',
        'RdgUsersStore',
        'DgsListStore',
        'DgsUsersStore',
        'RdgDgsStore'
    ],
    views: [
        'PersonalDetail',
        'UsersList',
        'PodeleniaList',
        'MainMenuPanel',
        'Main',
        'IagUsersList',
        'RdgList',
        'RdgUsersList',
        'RdgDgsList',
        'DgsTaList',
        'DgsUsersList'
    ],
    controllers: [
        'Main',
        'Func',
        'IagController',
        'AboutController',
        'RdgController',
        'PodController'
    ],
    name: 'Tel',

    launch: function() {

        Ext.create('Tel.view.Main', {fullscreen: true});
    }

});
