/*
 * File: app/controller/AllUsersSearch.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.controller.AllUsersSearch', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            search: {
                selector: '#search',
                xtype: 'Ext.field.Search'
            },
            alluserslist: '#alluserslist'
        },

        control: {
            "#search": {
                keyup: 'onSearchfieldKeyup'
            },
            "list": {
                itemtap: 'onListItemTap'
            },
            "searchfield": {
                clearicontap: 'onSearchfieldClearicontap'
            }
        }
    },

    onSearchfieldKeyup: function(textfield, e, eOpts) {


        var store = Ext.getStore('Store');

        value = textfield.getValue();

        this.getAlluserslist().setPlugins(null);

        store.clearFilter();

        store.currentPage = 1;


        if (value.length === 0) {
            store.clearFilter();
        }

        if (value.length < 1) {
            return;
        }


        if(value){

            var val = value.split(' ');

            if(val.length == 1){

                store.getProxy().setExtraParams({Ime:val[0], Fam:val[1]});

            }

            if(val.length == 2){

                store.getProxy().setExtraParams({Ime:val[0], Fam:val[1]});

            }

            console.log(val[0],val[1]);
        }


        store.load();
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {

        document.location.href = 'tel:'+record.data.tel;

    },

    onSearchfieldClearicontap: function(textfield, e, eOpts) {


        var store = Ext.getStore('Store');


        store.clearFilter();

        store.currentPage = 1;

        store.load();

    }

});