/*
 * File: app/controller/Func.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.controller.Func', {
    extend: 'Ext.app.Controller',
    alias: 'controller.func',

    config: {
        refs: {
            main: 'navigationview#main'
        }
    },

    loadStore: function(store) {


        var store = Ext.getStore(store);

        store.setAutoLoad('false');

        Ext.Viewport.setMasked({xtype:'loadmask', message:'Зареждам ...', indicator:true });

        store.clearFilter();

        store.load({
            callback: function(records, operation, success) {
                if(success)
                {
                    Ext.Viewport.setMasked(false);
                } else {
                    Ext.Viewport.setMasked(false);
                    Ext.Msg.alert('Събщение', 'Проверете връзката с интернет и рестартирайте приложението', Ext.emptyFn);
                }
            }
        });
    },

    clearList: function(store, url) {
        var store = Ext.getStore(store);
        store.clearFilter();
        store.getProxy().setUrl(url);
        this.loadStore(store);
        Ext.Viewport.setMasked(false);
    }

});