/*
 * File: app/controller/RdgController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tel.controller.RdgController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.rdgcontroller',

    config: {
        refs: {
            main: '#main',
            rdgBtn: 'button#rdgBtn',
            rdglist: 'list#rdglist',
            rdguserslist: 'list#rdguserslist'
        },

        control: {
            "rdgBtn": {
                tap: 'onRdgBtnTap'
            },
            "rdglist": {
                itemtap: 'onRdgListItemTap'
            },
            "rdguserslist": {
                itemtap: 'onRdgUserslistItemTap'
            }
        }
    },

    onRdgBtnTap: function(button, e, eOpts) {
        this.getMain().push({
            xtype: 'rdglist',
            title: 'РДГ/ ДП / ИАГ поделения'
        });

    },

    onRdgListItemTap: function(dataview, index, target, record, e, eOpts) {
        var store = Ext.getStore('RdgUsersStore'),
            podid = record.get('pod_id'),
            main = this.getMain();

        Ext.Viewport.setMasked({xtype:'loadmask', message:'Зареждам ...', indicator:true });

        store.load({
            params: {
                podid:podid
            },
            autoLoad: true,
            callback: function(records, operation, success) {
                if(success && records)
                {
                    Ext.Viewport.setMasked(false);
                    main.push({
                        xtype:'rdguserslist',
                        title: record.get('podelenie'),
                        data: record.data
                    });

                } else {
                    Ext.Viewport.setMasked(false);
                    Ext.Msg.alert('Събщение', 'Проверете връзката с интернет и рестартирайте приложението', Ext.emptyFn);
                }
            }
        });
    },

    onRdgUserslistItemTap: function(dataview, index, target, record, e, eOpts) {
        this.getMain().push({
            xtype: 'personaldetail',
            title: record.get('titla') + ' ' + record.get('ime') + ' ' + record.get('fam'),
            data: record.data,

            layout: 'vbox',
            items: [
                {
                    xtype: 'panel',
                    docked: 'top',
                    flex: 1,
                    margin: 10,
                    tpl: [
                        '<table style="text-align:center">',
                        '    <tr>',
                        '        <td style="padding:5px"><img src="https://vasil.iag.bg/upload/{glav_pod}/{picture}" width="140" heigh="140">',
                        '    </td>      ',
                        '    <tr>',
                        '        <td><small>Поделение: </small><b>{pod}</td>',
                        '    </tr>',
                        '    <tr>',
                        '        <td><small>Моб. тел: </small><b>{tel}</b></td>',
                        '    </tr>',
                        '    <tr>',
                        '        <td><small>Email: </small><b>{email}</b></td>',
                        '    </tr>',
                        '    <tr>',
                        '        <td><small>Длъжност: </small><b>{dlagnost}</b></td>',
                        '    </tr>',
                        '    <tr>',
                        '        <td><small>Дирекция: </small><b>{directorate_badj}</b></td>',
                        '    </tr>  ',
                        '   ',
                        '</table>'
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    docked: 'bottom',
                    padding: 50,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            text: 'Тел',
                            padding: 10,
                            ui: 'action-small',
                            disabled : (record.data.tel === 'Не е посочен телефон') ? true : false,
                            handler: function() {
                                document.location.href = 'tel:'+record.data.tel;
                            }
                        },
                        {
                            xtype: 'spacer',
                            width: 10
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            text: 'Email',
                            padding: 10,
                            ui: 'action-small',
                            disabled : (record.data.email === 'Не е посочен email') ? true : false,
                            handler: function() {
                                document.location.href = 'mailto:' + record.data.email;
                            }
                        },
                        {
                            xtype: 'spacer',
                            width: 10
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            text: 'SMS',
                            padding: 10,
                            ui: 'action-small',
                            disabled : (record.data.tel === 'Не е посочен телефон') ? true : false,
                            handler: function() {
                                document.location.href = 'sms:' + record.data.tel;
                            }
                        }
                    ]
                },

            ]

        });
    }

});